# Generated by Django 3.0.5 on 2020-05-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20200502_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='rating',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
