# Generated by Django 3.0.5 on 2020-05-12 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_title_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='rating',
        ),
    ]
